os: linux
dist: bionic #https://docs.travis-ci.com/user/reference/overview/
language: bash
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
matrix:
  include:
#########################################
####  SteamCMD Base Image
#########################################
    - name: SteamCMD Install
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --compress -t epicmorg/steamcmd:latest linux/steamcmd


